/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.util.ArrayList;

/**
 *
 * @author sergo
 */
public class Project extends javax.swing.JFrame {

    static int sp, rp, counter;
    static double size, ssum, rsum;
    static ArrayList<String> sendToMAC, recieveFromMAC, recieveFromIP, sendToIP, sendPacketPorts, recievePacketPorts, apps;

    /**
     * Creates new form Project
     */
    public Project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMac = new javax.swing.JTextArea();
        bFindMac = new javax.swing.JButton();
        txMac = new javax.swing.JTextField();
        bClients = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        readText = new javax.swing.JTextArea();
        bCheckNeighbors = new javax.swing.JButton();
        Lentermac = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taMac.setColumns(20);
        taMac.setRows(5);
        jScrollPane1.setViewportView(taMac);

        bFindMac.setText("Find Information");
        bFindMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFindMacActionPerformed(evt);
            }
        });

        txMac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txMacActionPerformed(evt);
            }
        });

        bClients.setText("Find common clients");
        bClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bClientsActionPerformed(evt);
            }
        });

        readText.setColumns(20);
        readText.setRows(5);
        jScrollPane2.setViewportView(readText);

        bCheckNeighbors.setText("Check neighbors");
        bCheckNeighbors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCheckNeighborsActionPerformed(evt);
            }
        });

        Lentermac.setText("         Enter MAC address");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCheckNeighbors, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(bFindMac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bClients, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Lentermac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txMac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lentermac, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txMac, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bFindMac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bClients)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCheckNeighbors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txMacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txMacActionPerformed

    private void bFindMacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFindMacActionPerformed
        sendToMAC = new ArrayList<>();
        recieveFromMAC = new ArrayList<>();
        recieveFromIP = new ArrayList<>();
        sendToIP = new ArrayList<>();
        sendPacketPorts = new ArrayList<>();
        recievePacketPorts = new ArrayList<>();
        apps = new ArrayList<>();
        sp = 0;
        rp = 0;
        size = 0;
        ssum = 0;
        rsum = 0;
        String mac = txMac.getText();
        if (mac.contains(":")&&mac.length()>=12) {
            //Functions.statistics("myfile-01", mac);
            //Functions.statistics("myfile-02", mac);

            taMac.setText("send packets to MAC " + sendToMAC.toString() + "\n"
                    + "recieved packets from MAC " + recieveFromMAC.toString() + "\n"
                    + "send packets to IP " + sendToIP.toString() + "\n"
                    + "recieved packets from IP " + recieveFromIP.toString() + "\n"
                    + "send average size " + ssum / sp + "\n"
                    + "recieve average size " + rsum / rp + "\n"
                    + "Packets recieved :" + rp + " Packets send :" + sp + "\n");

            for (int i = 0; i < apps.size(); i++) {
                taMac.setText(taMac.getText() + apps.get(i) + "\n");
            }

        } else {
            Lentermac.setText("Wrong MAC address");
        }
    }//GEN-LAST:event_bFindMacActionPerformed

    private void bClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bClientsActionPerformed
        readText.setText("");
        ArrayList<Client> Cl1 = new ArrayList<>(Functions.readClients("1"));
        ArrayList<Client> Cl2 = new ArrayList<>(Functions.readClients("2"));
        ArrayList<Client> Cl0 = new ArrayList<>();
        for (Client Cl11 : Cl1) {
            for (int j = 0; j < Cl2.size(); j++) {
                if (Cl2.get(j).mac.contains(Cl11.mac)) {
                    Cl0.add(Cl2.remove(j));
                }
            }
        }
        for (Client Cl01 : Cl0) {
            readText.setText(readText.getText() + Functions.getMACVendor(Cl01.mac) + "\n");
        }
    }//GEN-LAST:event_bClientsActionPerformed

    private void bCheckNeighborsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCheckNeighborsActionPerformed
        ArrayList<Client> Cl1 = new ArrayList<>(Functions.readClients("1"));
        ArrayList<Client> Cl2 = new ArrayList<>(Functions.readClients("2"));
        ArrayList<Client> Cl0 = new ArrayList<>();
        taMac.setText(taMac.getText() + "Checking neighbors :" + "\n");
        boolean n = true;
        for (Client Cl11 : Cl1) {
            if (sendToMAC.contains(Cl11.mac) || recieveFromMAC.contains(Cl11.mac)) {
                taMac.setText(taMac.getText() + Cl11.mac + " Seen at point 1" + "\n");
                n = false;
            }
        }

        for (Client Cl22 : Cl2) {
            if (sendToMAC.contains(Cl22.mac) || recieveFromMAC.contains(Cl22.mac)) {
                taMac.setText(taMac.getText() + Cl22.mac + " Seen at point 2" + "\n");
                n = false;
            }

        }
        if (n) {
            taMac.setText(taMac.getText() + "neighbors not seen" + "\n");
        }
    }//GEN-LAST:event_bCheckNeighborsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Project().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lentermac;
    private javax.swing.JButton bCheckNeighbors;
    private javax.swing.JButton bClients;
    private javax.swing.JButton bFindMac;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea readText;
    private javax.swing.JTextArea taMac;
    private javax.swing.JTextField txMac;
    // End of variables declaration//GEN-END:variables
}
